# Root site configuration
[build]
  base = "/"
  command = "npm run build:all"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./tools/task-smasher/"

# TaskSmasher app configuration
[context.production.environment]
  NODE_ENV = "production"

# Redirects for the root site
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Redirects for the TaskSmasher app
[[redirects]]
  from = "/tools/task-smasher/*"
  to = "/tools/task-smasher/index.html"
  status = 200

# Specific redirects for TaskSmasher use cases
[[redirects]]
  from = "/tools/task-smasher/marketing-tasks/*"
  to = "/tools/task-smasher/marketing-tasks/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/daily-organizer/*"
  to = "/tools/task-smasher/daily-organizer/index.html"
  status = 200

[[redirects]]
  from = "/tools/task-smasher/goal-planner/*"
  to = "/tools/task-smasher/goal-planner/index.html"
  status = 200

# API redirects for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Catch-all redirect for SPA - must be at the very bottom
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200